# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build Beta"
  lane :build_beta do
    build_number = number_of_commits()
    Dir.chdir "../" do
      sh("flutter", "packages", "get")
      sh("flutter", "clean")
      sh("flutter", "build", "appbundle", "--flavor=beta", "--build-number=#{build_number}", "--dart-define=API_BASE_URL=https://apiurlbeta.com")
    end

    upload_to_play_store(
      track: 'internal',
      release_status: 'draft',
      aab: '../build/app/outputs/bundle/betaRelease/app-beta-release.aab'
    )
  end

  desc "Deploy Production"
  lane :build_production do
    build_number = number_of_commits()
    Dir.chdir "../" do
      sh("flutter", "packages", "get")
      sh("flutter", "clean")
      sh("flutter", "build", "appbundle", "--flavor=production", "--build-number=#{build_number}", "--dart-define=API_BASE_URL=https://apiurlprod.com")
    end

    upload_to_play_store(
      package_name: 'com.surkus.local',
      track: 'internal',
      release_status: 'draft',
      aab: '../build/app/outputs/bundle/productionRelease/app-production-release.aab'
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
