name: device
description: Device layer

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ^2.10.5

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.1.3
  shared_preferences: ^2.0.5
  flutter_riverpod: ^1.0.3
  package_info: ^2.0.2
  image_picker: ^0.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
