name: repository
description: Repository layer

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ^2.2.0

dependencies:
  flutter:
    sdk: flutter
  get_it: 5.0.4
  shared_preferences: ^0.5.12
  http: ^0.12.2
  retrofit: any
  logger: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  retrofit_generator: any
  build_runner: any

flutter:
  uses-material-design: true
